DROP TABLE IF EXISTS authors;
DROP TABLE IF EXISTS books;

CREATE TABLE  authors(
id INT AUTO_INCREMENT,
author VARCHAR(250) NOT NULL,
PRIMARY KEY(id)
);

CREATE TABLE  books(
id INT PRIMARY KEY AUTO_INCREMENT,
authorID INT,
title VARCHAR(250) NOT NULL,
priceOld  VARCHAR(250) DEFAULT NULL,
price VARCHAR(250) DEFAULT NULL,
FOREIGN KEY(authorID) REFERENCES authors(id)
);

